/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MorpionVue.java
 *
 * Created on 27 sept. 2010, 09:45:40
 */


import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author sebilleg
 */
public class MorpionVue extends javax.swing.JPanel {

    Morpion Mor;

    /** Creates new form MorpionVue */
    public MorpionVue() {
        Mor = new Morpion();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 1, 1));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(133, 100));
        jButton1.setMinimumSize(new java.awt.Dimension(133, 100));
        jButton1.setPreferredSize(new java.awt.Dimension(133, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(133, 100));
        jButton2.setMinimumSize(new java.awt.Dimension(133, 100));
        jButton2.setPreferredSize(new java.awt.Dimension(134, 100));

        jButton3.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(133, 100));
        jButton3.setMinimumSize(new java.awt.Dimension(133, 100));
        jButton3.setPreferredSize(new java.awt.Dimension(133, 100));

        jButton4.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton4.setText("jButton4");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setPreferredSize(new java.awt.Dimension(133, 100));

        jButton5.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton5.setText("jButton5");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setPreferredSize(new java.awt.Dimension(134, 100));

        jButton6.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton6.setText("jButton6");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setMaximumSize(new java.awt.Dimension(133, 100));
        jButton6.setMinimumSize(new java.awt.Dimension(133, 100));
        jButton6.setPreferredSize(new java.awt.Dimension(133, 100));

        jButton7.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton7.setText("jButton7");
        jButton7.setBorderPainted(false);
        jButton7.setPreferredSize(new java.awt.Dimension(133, 100));

        jButton8.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton8.setText("jButton8");
        jButton8.setBorderPainted(false);
        jButton8.setPreferredSize(new java.awt.Dimension(134, 100));

        jButton9.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/vide.jpg")); // NOI18N
        jButton9.setText("jButton9");
        jButton9.setBorderPainted(false);
        jButton9.setPreferredSize(new java.awt.Dimension(133, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setBackground(new java.awt.Color(1,1,1));
        if(Mor.cKiKiJoue) {
            if(Mor.plateau[0][0] != 0) {
                jButton1.setIcon(new ImageIcon("/home/infoetu/chapotat/Images/croix.jpg"));
                Mor.cKiKiJoue = !Mor.cKiKiJoue;
                Mor.plateau[0][0] = 1;
            }else{
                   System.out.println("LOOL, t'as cru !");
            }
            
        }else{
            if(Mor.plateau[0][0] != 0) {
                 jButton1.setIcon(new ImageIcon("/home/infoetu/chapotat/Images/rond.jpg"));
                 Mor.cKiKiJoue = !Mor.cKiKiJoue;
                 Mor.plateau[0][0] = 1;
            }else{
                   System.out.println("LOOL, t'as cru !");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables



    public static void main(String[] args) {
        JFrame jf = new JFrame();
        MorpionVue mv = new MorpionVue();
        jf.add(mv);
        jf.setVisible(true);
    }
}
