/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrpionVue.java
 *
 * Created on 4 oct. 2010, 10:24:22
 */

package doodlegames;

import javax.swing.ImageIcon;

/**
 *
 * @author somet
 */
public class MorpionVue extends javax.swing.JPanel {
    MorpionModele mod = new MorpionModele();
    /** Creates new form OrpionVue */
    public MorpionVue() {
        initComponents();
       // this.go();
    }



    /*public void jouerCoup(int x , int y , int joueur){
        if(this.mod.getCase(x,y) == 0){
            this.mod.fillCase(x,y);
            return;
        }

        while(this.mod.getCase(x,y) != 0)
        {
            if(this.mod.getCase(x,y) == 0){
            	this.mod.fillCase(x,y);
                return;
            }
        }
    }*/

    public void afficher(){
        for(int i = 0 ; i < 3 ; i++)
        {
               for(int j = 0 ; j < 3 ; j++)
               {
                   if(this.mod.getCase(i,j) == 1)
                       System.out.print(" X ");
                   else if(this.mod.getCase(i,j) == 2)
                       System.out.print(" 0 ");
                   else
                       System.out.print(" _ ");

                   if( j != 2 )
                       System.out.print("|");
               }
            if( i != 2 )
                System.out.print("\n---+---+---\n");
        }
        System.out.println("\n\n");
    }

    public void finDePartie(){
       if((this.mod.getCase(0,0) != 0 && this.mod.getCase(0,0) == this.mod.getCase(0,1) && this.mod.getCase(0,1) == this.mod.getCase(0,2)) ||
               (this.mod.getCase(1,0) != 0 && this.mod.getCase(1,0) == this.mod.getCase(1,1) && this.mod.getCase(1,1) == this.mod.getCase(1,2)) ||
               (this.mod.getCase(2,0) != 0 && this.mod.getCase(2,0) == this.mod.getCase(2,1) && this.mod.getCase(2,1) == this.mod.getCase(2,2)) ||
               (this.mod.getCase(0,0) != 0 && this.mod.getCase(0,0) == this.mod.getCase(1,0) && this.mod.getCase(1,0) == this.mod.getCase(2,0)) ||
               (this.mod.getCase(0,1) != 0 && this.mod.getCase(0,1) == this.mod.getCase(1,1) && this.mod.getCase(1,1) == this.mod.getCase(2,1)) ||
               (this.mod.getCase(0,2) != 0 && this.mod.getCase(0,2) == this.mod.getCase(1,2) && this.mod.getCase(1,2) == this.mod.getCase(2,2)) ||
               (this.mod.getCase(0,0) != 0 && this.mod.getCase(0,0) == this.mod.getCase(1,1) && this.mod.getCase(1,1) == this.mod.getCase(2,2)) ||
               (this.mod.getCase(0,2) != 0 && this.mod.getCase(0,2) == this.mod.getCase(1,1) && this.mod.getCase(1,1) == this.mod.getCase(2,0)))
            System.out.println("Joueur 1 gagne!");
        else if (this.mod.getCase(0,0) != 0 && this.mod.getCase(0,1) != 0 && this.mod.getCase(0,2) != 0 &&
                 this.mod.getCase(1,0) != 0 && this.mod.getCase(1,1) != 0 && this.mod.getCase(1,2) != 0 &&
                 this.mod.getCase(2,0) != 0 && this.mod.getCase(2,1) != 0 && this.mod.getCase(2,2) != 0 )
            System.out.println("Joueur 2 gagne!");
    }

    /*public void go(){
        int a , b , c = 0;
        while(this.finDePartie() == 0){
           a = (int)(100*Math.random())%3;
           b = (int)(100*Math.random())%3;
           c += 1;
           this.jouerCoup(a, b, c);
           c %= 2;
           this.afficher();
        }
        if (this.finDePartie() == 1)
            System.out.println("Bien joué !!!");
        else
            System.out.println("Dommage");
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 1, 1));

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(1, 1, 1));
        jButton2.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(1, 1, 1));
        jButton3.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(1, 1, 1));
        jButton4.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(1, 1, 1));
        jButton5.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(1, 1, 1));
        jButton6.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(1, 1, 1));
        jButton7.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(1, 1, 1));
        jButton8.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(1, 1, 1));
        jButton9.setIcon(new javax.swing.ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/vide.jpg")); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addComponent(jButton1))
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.mod.fillCase(0, 0);
        System.out.println(this.mod.getCase(0, 0));
        if(this.mod.getCase(0, 0) == 1)
            jButton1.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(0, 0) == 2)
            jButton1.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton1.setEnabled(false);
        this.afficher();
        this.finDePartie();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.mod.fillCase(0, 1);
        if(this.mod.getCase(0, 1) == 1)
            jButton2.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(0, 1) == 2)
            jButton2.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton2.setEnabled(false);
        this.afficher();
        this.finDePartie();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.mod.fillCase(0, 2);
        if(this.mod.getCase(0, 2) == 1)
            jButton3.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(0, 2) == 2)
            jButton3.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton3.setEnabled(false);
        this.afficher();
        this.finDePartie();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.mod.fillCase(1, 0);
        if(this.mod.getCase(1, 0) == 1)
            jButton4.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(1, 0) == 2)
            jButton4.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton4.setEnabled(false);
        this.afficher();
        this.finDePartie();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.mod.fillCase(1, 1);
        if(this.mod.getCase(1, 1) == 1)
            jButton5.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(1, 1) == 2)
            jButton5.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton5.setEnabled(false);
        this.afficher();
        this.finDePartie();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.mod.fillCase(1, 2);
        if(this.mod.getCase(1, 2) == 1)
            jButton6.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(1, 2) == 2)
            jButton6.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton6.setEnabled(false);
        this.afficher();
        this.finDePartie();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         this.mod.fillCase(2, 0);
        if(this.mod.getCase(2, 0) == 1)
            jButton7.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(2, 0) == 2)
            jButton7.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
         jButton7.setEnabled(false);
        this.afficher();
         this.finDePartie();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.mod.fillCase(2, 1);
        if(this.mod.getCase(2, 1) == 1)
            jButton8.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));

        else if(this.mod.getCase(2, 1) == 2)
            jButton8.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton8.setEnabled(false);
        this.afficher();
        this.finDePartie();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.mod.fillCase(2, 2);
        if(this.mod.getCase(2, 2) == 1)
            jButton9.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/croix.jpg"));
        else if(this.mod.getCase(2, 2) == 2)
            jButton9.setIcon(new ImageIcon("/home/infoetu/somet/DoodleGames/Morpion/Images/rond.jpg"));
        jButton9.setEnabled(false);
        this.afficher();
        this.finDePartie();
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

    /*public static void main(String args[]){
        MorpionVue Test = new MorpionVue();
    }*/

}
