/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * window.java
 *
 * Created on 13 sept. 2010, 10:28:08
 */

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author chapotat
 */
public class Window extends javax.swing.JFrame {
    public String game;

    /** Creates new form window */
    public window() {
        initComponents();
        j1label.setText("Score "+j1edit.getText()+" : ");
        j2label.setVisible(false);
        scorej2.setVisible(false);
        gameframe.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        facile = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        difficile = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gamename = new javax.swing.JLabel();
        ia = new javax.swing.JLabel();
        ialabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j1label = new javax.swing.JLabel();
        j2label = new javax.swing.JLabel();
        scorej1 = new javax.swing.JLabel();
        scorej2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iacheck = new javax.swing.JCheckBox();
        jcheck = new javax.swing.JCheckBox();
        j2edit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        j1edit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        gameframe = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(null);

        jToggleButton1.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/exemple.jpg")); // NOI18N
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setHideActionText(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/puissan5.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("/home/infoetu/chapotat/Images/SimonIcone.jpg")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Option IA :");

        facile.setText("Facile");
        facile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facileActionPerformed(evt);
            }
        });

        normal.setText("Normal");
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        difficile.setText("Difficile");
        difficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficileActionPerformed(evt);
            }
        });

        jLabel2.setText("Informations :");

        jLabel3.setText("Jeu :");

        gamename.setText("en attente.");

        ia.setText("IA :");

        ialabel.setText("non.");

        jLabel8.setText("Temp restant :");

        j1label.setText("Score joueur 1 :");

        j2label.setText("Score joueur 2 :");

        scorej1.setText("0.");

        scorej2.setText("0.");

        jLabel13.setText("0.");

        iacheck.setText("IA");
        iacheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iacheckActionPerformed(evt);
            }
        });

        jcheck.setText("Joueur");
        jcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckActionPerformed(evt);
            }
        });

        j2edit.setText("J2");
        j2edit.setEnabled(false);

        jLabel5.setText("Nom joueur 1:");

        j1edit.setText("J1");

        jLabel7.setText("VS");

        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        gameframe.setVisible(true);

        javax.swing.GroupLayout gameframeLayout = new javax.swing.GroupLayout(gameframe.getContentPane());
        gameframe.getContentPane().setLayout(gameframeLayout);
        gameframeLayout.setHorizontalGroup(
            gameframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        gameframeLayout.setVerticalGroup(
            gameframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gameframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j2label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scorej2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j1label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(scorej1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ialabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(gamename)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(j1edit, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jcheck)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(j2edit)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iacheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(normal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(difficile, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(facile))))
                        .addContainerGap(74, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(592, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameframe)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(gamename))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ia)
                            .addComponent(ialabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j1label)
                            .addComponent(scorej1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j2label)
                            .addComponent(scorej2)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(j1edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcheck)
                            .addComponent(j2edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(iacheck)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(facile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(normal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(difficile))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facileActionPerformed
        // TODO add your handling code here:
        normal.setSelected(false);
        difficile.setSelected(false);
        //ialabel.setText("Facile.");
    }//GEN-LAST:event_facileActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
        facile.setSelected(false);
        difficile.setSelected(false);
        //ialabel.setText("Normale.");
    }//GEN-LAST:event_normalActionPerformed

    private void difficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficileActionPerformed
        facile.setSelected(false);
        normal.setSelected(false);
        //ialabel.setText("Difficile.");
        // TODO add your handling code here:
    }//GEN-LAST:event_difficileActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
            gamename.setText("Morpion.");
            game="morpion";
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                int cpt=0;
                game="simon";
        if (j1edit.getText().equals("")){
            cpt=7;
        }


        if (cpt==0){
            gamename.setText("Simon.");
        }else{
            j1erreur e3=new j1erreur();
            e3.main(null);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gamename.setText("Puissance 4.");
        game="puissance4";
    }//GEN-LAST:event_jButton1ActionPerformed

    private void iacheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iacheckActionPerformed
        // TODO add your handling code here:
             if (iacheck.isSelected()){
            facile.setEnabled(true);
            normal.setEnabled(true);
            difficile.setEnabled(true);
            jcheck.setEnabled(false);
        }else{
        facile.setEnabled(false);
        normal.setEnabled(false);
        difficile.setEnabled(false);
        jcheck.setEnabled(true);
        }
    }//GEN-LAST:event_iacheckActionPerformed

    private void jcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckActionPerformed
        // TODO add your handling code here:

        if (jcheck.isSelected()){
            iacheck.setEnabled(false);
            j2edit.setEnabled(true);
        }else{
            j2edit.setEnabled(false);
            iacheck.setEnabled(true);
        }

    }//GEN-LAST:event_jcheckActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        j1label.setText("Score "+j1edit.getText()+" : ");
        j2label.setText("Score "+j2edit.getText()+" : ");
            ialabel.setVisible(true);
            ia.setVisible(true);
            j2label.setVisible(true);
            scorej2.setVisible(true);

        if (iacheck.isSelected()){

            if (facile.isSelected()){
                   ialabel.setText("Facile.");
                   j2label.setText("Score IA Facile : ");
            }
                        if (normal.isSelected()){
                   ialabel.setText("Normale.");
                   j2label.setText("Score IA Normal : ");
            }
                        if (difficile.isSelected()){
                   ialabel.setText("Difficile.");
                   j2label.setText("Score IA Difficile : ");
            }
        }

                if(jcheck.isSelected()){
            simonerreur e2=new simonerreur();
            e2.main(null);

        }else if (iacheck.isSelected()){
            simonerreur e2=new simonerreur();
            e2.main(null);
        }

        if (jcheck.isSelected()){
            scorej2.setVisible(true);
            iacheck.setEnabled(false);
            j2edit.setEnabled(true);
        }else{
            scorej2.setVisible(false);
            j2edit.setEnabled(false);
            iacheck.setEnabled(true);
        }

        
        if (iacheck.isSelected()){
            facile.setEnabled(true);
            normal.setEnabled(true);
            difficile.setEnabled(true);
            jcheck.setEnabled(false);
        }else{
            ialabel.setText("non.");
        facile.setEnabled(false);
        normal.setEnabled(false);
        difficile.setEnabled(false);
        jcheck.setEnabled(true);
        }
        j2label.setVisible(true);
        scorej2.setVisible(true);

        if (game.equals("simon") && !jcheck.isSelected() && !iacheck.isSelected()){
            ialabel.setVisible(false);
            ia.setVisible(false);
            j2label.setVisible(false);
            scorej2.setVisible(false);
            
            
            Animation a = new Animation();
            a.start();

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */



    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton difficile;
    public javax.swing.JRadioButton facile;
    public static javax.swing.JInternalFrame gameframe;
    private javax.swing.JLabel gamename;
    private javax.swing.JLabel ia;
    private javax.swing.JCheckBox iacheck;
    private javax.swing.JLabel ialabel;
    private javax.swing.JTextField j1edit;
    private javax.swing.JLabel j1label;
    private javax.swing.JTextField j2edit;
    private javax.swing.JLabel j2label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JCheckBox jcheck;
    public javax.swing.JRadioButton normal;
    private javax.swing.JLabel scorej1;
    private javax.swing.JLabel scorej2;
    // End of variables declaration//GEN-END:variables

}
