/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimonVue.java
 *
 * Created on 13 sept. 2010, 10:34:12
 */

import java.util.Observable;
import java.util.Observer;

import javax.swing.*;

/**
 *
 * @author thuillij
 */


public class SimonVue extends javax.swing.JPanel implements Observer{
    /** Creates new form SimonVue */
    
    ModelSimon mod ;
    
    
    public SimonVue() {
    	this.mod = new ModelSimon();
    	mod.addObserver(this);

        initComponents();
        setVisible(true);
        
    	JFrame f = new JFrame();
    	f.setBounds(300,300,400,300);
  
    	f.add(this);
    	f.setVisible(true);

    	window.gameframe.add(this);
    	f.dispose();
    	window.gameframe.repaint();

    	
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setAlignmentX(0.0F);
        setLayout(new java.awt.GridLayout(2, 2));

        jButton1.setIcon(new javax.swing.ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg")); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(200, 150));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }

             public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg")); // NOI18N
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorderPainted(false);
        jButton2.setPreferredSize(new java.awt.Dimension(200, 150));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg")); // NOI18N
        jButton3.setAlignmentY(0.0F);
        jButton3.setBorderPainted(false);
        jButton3.setPreferredSize(new java.awt.Dimension(200, 150));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
             public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg")); // NOI18N
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorderPainted(false);
        jButton4.setPreferredSize(new java.awt.Dimension(200, 150));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
             public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        add(jButton4);
    }// </editor-fold>//GEN-END:initComponents



    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       // mod.setBoutonClique(0);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1Change.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
    }//GEN-LAST:event_jButton1MouseClicked

        private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        mod.setBoutonClique(0);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
        /*if (mod.gagne)
        {
        	mod.gagne = false;
        	mod.clearSeq();
        	mod.initSeq(5);
        }*/
        }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       // mod.setBoutonClique(1);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2Change.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
   
    }//GEN-LAST:event_jButton2MouseClicked

        private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        mod.setBoutonClique(1);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
        /*if (mod.gagne == true)
        {
        	mod.gagne = false;
        	mod.clearSeq();
        	mod.initSeq(5);
        }*/
        }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
     //   mod.setBoutonClique(2);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3Change.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
    }//GEN-LAST:event_jButton3MouseClicked

        private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        mod.setBoutonClique(2);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
        /*if (mod.gagne)
        {
        	mod.gagne = false;
        	mod.clearSeq();
        	mod.initSeq(5);
        }*/
    }//GEN-LAST:event_jButton3MouseClicked


    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      //  mod.setBoutonClique(3);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4Change.jpg"));
    }//GEN-LAST:event_jButton4MouseClicked

       private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        mod.setBoutonClique(3);
        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
        jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
        jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
        jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
        /*if (mod.gagne)
        {
        	mod.gagne = false;
        	mod.clearSeq();
        	mod.initSeq(5);
        }*/
    }//GEN-LAST:event_jButton4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
    

	@Override
	public void update(Observable arg0, Object arg1) {

		for (int i = 0 ; i<mod.seqList.size();i++)
		{	
			if ( mod.seqList.get(i) == 0)
			{
		        jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1Change.jpg"));
		        try {
					Thread.sleep(700);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	        	repaint();
	        	revalidate();
	        	repaint();
				jButton1.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg1.jpg"));
				try {
					Thread.sleep(200);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				repaint();
	        	revalidate();
	        	repaint();
			}
			else if ( mod.seqList.get(i) == 1)
			{
				 jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2Change.jpg"));
			        try {
						Thread.sleep(700);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					repaint();
		        	revalidate();
		        	repaint();
					jButton2.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg2.jpg"));
					try {
						Thread.sleep(200);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					repaint();
		        	revalidate();
		        	repaint();
			}
			else if ( mod.seqList.get(i) == 2)
			{
				 jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3Change.jpg"));
			        try {
						Thread.sleep(700);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					repaint();
		        	revalidate();
		        	repaint();
					jButton3.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg3.jpg"));
					try {
						Thread.sleep(200);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					repaint();
		        	revalidate();
		        	repaint();
			}
			else if ( mod.seqList.get(i) == 3)
			{

				 jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4Change.jpg"));
			        try {
						Thread.sleep(700);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					repaint();
		        	revalidate();
		        	repaint();
					jButton4.setIcon(new ImageIcon("/home/infoetu/khelilr/Bureau/SimonImg4.jpg"));
					try {
						Thread.sleep(200);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					repaint();
		        	revalidate();
		        	repaint();
			}
		}
	}
    
    public static void main(String [] args)
    {
    	/*
    	JFrame f = new JFrame();
    	f.setBounds(300,300,400,300);
    	
    	SimonVue v = new SimonVue();
    	f.add(v);
    	f.setVisible(true);*/
    	//SimonVue s = new SimonVue();
    
    }


}